### ISSUE TITLE
建议加入可以更改group配置的功能

### ISSUE THREAD

**Issue by GtGuiZhou** [laravel-admin-extensions/large-file-upload#7]

**Comment by GtGuiZhou** [comment]
`class LargeFileField extends Field
{

    public $view = 'large-file-field::large_file_upload';

    public function render()
    {
        $name = $this->formatName($this->column);

        $this->script = <<<SRC

        $('#{$name}-file').bootstrapFileInput();
        $('#{$name}-file').change(function(){
             aetherupload('{$name}', this, 'file').success(getPath).upload('{$name}'); // 这一行代码
           // aetherupload('{$name}', this, '希望这个参数能够动态更改').success(getPath).upload('{$name}'); 
        });

SRC;
        return parent::render();
    }
}`

**Comment by Dianwoung** [comment]
先追上主依赖包的进度吧，会认真考虑的
